import * as React from 'react';
import { Task, Routine, FocusSession, Habit, Project, Priority } from '../types';
import { ChevronLeft, ChevronRight, Clock, X, Calendar as CalIcon, ZoomIn, ZoomOut, PlayCircle, CheckCircle2, Focus, Layers, PanelLeft, LayoutGrid, ListTodo, Book, Briefcase, Eye, EyeOff, CalendarPlus, ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Minus, Plus, CalendarOff, Move, CheckSquare, Droplets, ChevronUp, ChevronDown } from 'lucide-react';

interface CalendarModuleProps {
  tasks: Task[];
  routines?: Routine[];
  habits?: Habit[]; 
  projects?: Project[];
  focusSessions?: FocusSession[];
  onUpdateTask: (task: Task) => void;
  onStartTask: (task: Task) => void;
  onScheduleRoutine?: (templateId: string, startTime: number) => void; 
  onStartRoutine?: (id: string) => void;
  onUpdateRoutine?: (routine: Routine) => void;
  onScheduleHabit?: (habitId: string, startTime: number) => void; 
  onUnschedule?: (id: string, type: 'task' | 'routine') => void;
}

type CalendarView = 'month' | 'week' | 'day';
type CalendarMode = 'scheduled' | 'focus';

const FOCUS_COLORS = [
  "hsl(174, 32%, 52%)", // primary-teal
  "hsl(19, 100%, 68%)", // accent-coral
  "hsl(35, 88%, 72%)", // reward-amber
  "hsl(256, 56%, 75%)", // tag-lavender
  "hsl(201, 10%, 53%)", // neutral-slate
  "hsl(158, 42%, 48%)", // success
];

export const CalendarModule: React.FC<CalendarModuleProps> = ({ 
    tasks, routines = [], habits = [], projects = [], focusSessions = [], onUpdateTask, onStartTask, onScheduleRoutine, onStartRoutine, onUpdateRoutine, onScheduleHabit, onUnschedule
}) => {
  const [view, setView] = React.useState<CalendarView>('week');
  const [mode, setMode] = React.useState<CalendarMode>('scheduled');
  const [currentDate, setCurrentDate] = React.useState(new Date());
  const [showCompleted, setShowCompleted] = React.useState(false);
  
  // Sidebar State
  const [isSidebarOpen, setIsSidebarOpen] = React.useState(false);
  const [isDraggingOverLibrary, setIsDraggingOverLibrary] = React.useState(false);

  // Zoom / Scaling State
  const [hourHeight, setHourHeight] = React.useState(60); 

  // Selection / Mobile Edit State
  const [selectedBlock, setSelectedBlock] = React.useState<{ id: string, type: 'task' | 'routine' } | null>(null);

  // Resizing State (Desktop)
  const [resizingTaskId, setResizingTaskId] = React.useState<string | null>(null);
  const resizeRef = React.useRef<{ startY: number; startDuration: number; taskId: string } | null>(null);
  
  const ignoreClickRef = React.useRef(false);

  // Real-time state
  const [now, setNow] = React.useState(new Date());
  
  // Refs for scroll syncing
  const scrollContainerRef = React.useRef<HTMLDivElement>(null);
  const headerContainerRef = React.useRef<HTMLDivElement>(null);

  // Derived Data
  const pendingTasks = React.useMemo(() => tasks.filter(t => !t.isCompleted && !t.deletedAt && !t.startTime), [tasks]);
  const recurringRoutines = React.useMemo(() => routines.filter(r => r.type === 'repeatable' && !r.deletedAt), [routines]);

  React.useEffect(() => {
    const interval = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(interval);
  }, []);

  React.useEffect(() => {
    if (scrollContainerRef.current) {
        const d = new Date();
        const minutes = d.getHours() * 60 + d.getMinutes();
        const pxPerMin = hourHeight / 60;
        scrollContainerRef.current.scrollTop = Math.max(0, (minutes - 60) * pxPerMin);
    }
  }, [view, hourHeight]); 

  // Sync horizontal scroll between header and body
  const handleBodyScroll = (e: React.UIEvent<HTMLDivElement>) => {
      if (headerContainerRef.current) {
          headerContainerRef.current.scrollLeft = e.currentTarget.scrollLeft;
      }
  };

  const handleScroll = (amount: number) => {
      if (scrollContainerRef.current) {
          scrollContainerRef.current.scrollBy({ top: amount, behavior: 'smooth' });
      }
  };

  const handleZoom = (amount: number) => {
      setHourHeight(prev => Math.max(40, Math.min(150, prev + amount)));
  };

  // --- Mobile Touch Logic (Touch Control Panel) ---

  const getTargetDateForQuickSchedule = () => {
      const targetDate = new Date(currentDate);
      const currentHour = new Date().getHours();
      if (isSameDay(targetDate, new Date())) {
          targetDate.setHours(currentHour + 1, 0, 0, 0);
      } else {
          targetDate.setHours(9, 0, 0, 0);
      }
      return targetDate.getTime();
  };

  const handleQuickScheduleTask = (task: Task) => {
      onUpdateTask({ ...task, startTime: getTargetDateForQuickSchedule() });
      setSelectedBlock({ id: task.id, type: 'task' });
      setIsSidebarOpen(false);
  };

  const handleQuickScheduleRoutine = (routine: Routine) => {
      if (onScheduleRoutine) {
          onScheduleRoutine(routine.id, getTargetDateForQuickSchedule());
          // We can't immediately select it because we don't know the new ID generated by App.tsx
          // But we can close sidebar
          setIsSidebarOpen(false);
      }
  };

  const handleQuickScheduleHabit = (habit: Habit) => {
      if (onScheduleHabit) {
          onScheduleHabit(habit.id, getTargetDateForQuickSchedule());
          setIsSidebarOpen(false);
      }
  };

  const moveSelectedItem = (minutes: number) => {
      if (!selectedBlock) return;
      
      if (selectedBlock.type === 'task') {
          const task = tasks.find(t => t.id === selectedBlock.id);
          if (task && task.startTime) {
              onUpdateTask({ ...task, startTime: task.startTime + (minutes * 60000) });
          }
      } else {
          const routine = routines.find(r => r.id === selectedBlock.id);
          if (routine && routine.startTime && onUpdateRoutine) {
              onUpdateRoutine({ ...routine, startTime: routine.startTime + (minutes * 60000) });
          }
      }
  };

  const shiftSelectedItemDay = (days: number) => {
      if (!selectedBlock) return;

      const updateTime = (startTime: number) => {
          const newDate = new Date(startTime);
          newDate.setDate(newDate.getDate() + days);
          return newDate.getTime();
      };

      if (selectedBlock.type === 'task') {
          const task = tasks.find(t => t.id === selectedBlock.id);
          if (task && task.startTime) {
              const newTime = updateTime(task.startTime);
              onUpdateTask({ ...task, startTime: newTime });
              if (view === 'day') setCurrentDate(new Date(newTime));
          }
      } else {
          const routine = routines.find(r => r.id === selectedBlock.id);
          if (routine && routine.startTime && onUpdateRoutine) {
              const newTime = updateTime(routine.startTime);
              onUpdateRoutine({ ...routine, startTime: newTime });
              if (view === 'day') setCurrentDate(new Date(newTime));
          }
      }
  };

  const resizeSelectedItem = (minutes: number) => {
      if (!selectedBlock || selectedBlock.type !== 'task') return;
      const task = tasks.find(t => t.id === selectedBlock.id);
      if (task) {
          const currentDuration = task.duration || 30;
          const newDuration = Math.max(15, currentDuration + minutes);
          onUpdateTask({ ...task, duration: newDuration });
      }
  };

  const unscheduleSelectedItem = () => {
      if (!selectedBlock) return;
      if (onUnschedule) {
          onUnschedule(selectedBlock.id, selectedBlock.type);
          setSelectedBlock(null);
      }
  };

  const startSelectedItem = () => {
      if (!selectedBlock) return;
      if (selectedBlock.type === 'task') {
          const task = tasks.find(t => t.id === selectedBlock.id);
          if (task) {
              onStartTask(task);
              setSelectedBlock(null);
          }
      } else {
           if (onStartRoutine) {
               onStartRoutine(selectedBlock.id);
               setSelectedBlock(null);
           }
      }
  };

  // --- Resizing Logic (Desktop Mouse) ---
  React.useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
        if (!resizeRef.current) return;
        
        const { startY, startDuration, taskId } = resizeRef.current;
        const deltaY = e.clientY - startY;
        const deltaMinutes = Math.round((deltaY / hourHeight) * 60);
        const snappedDelta = Math.round(deltaMinutes / 10) * 10;
        const newDuration = Math.max(10, startDuration + snappedDelta); 

        const task = tasks.find(t => t.id === taskId);
        if (task && task.duration !== newDuration) {
            onUpdateTask({ ...task, duration: newDuration });
        }
    };

    const handleMouseUp = () => {
        if (resizingTaskId) {
            setResizingTaskId(null);
            resizeRef.current = null;
            ignoreClickRef.current = true;
            setTimeout(() => {
                ignoreClickRef.current = false;
            }, 100);
        }
    };

    if (resizingTaskId) {
        window.addEventListener('mousemove', handleMouseMove);
        window.addEventListener('mouseup', handleMouseUp);
    }

    return () => {
        window.removeEventListener('mousemove', handleMouseMove);
        window.removeEventListener('mouseup', handleMouseUp);
    };
  }, [resizingTaskId, hourHeight, tasks, onUpdateTask]);

  const handleResizeStart = (e: React.MouseEvent, task: Task) => {
    e.preventDefault();
    e.stopPropagation(); 
    setResizingTaskId(task.id);
    resizeRef.current = {
        taskId: task.id,
        startY: e.clientY,
        startDuration: task.duration || 60
    };
  };

  // --- Helpers ---
  const getStartOfWeek = (date: Date) => {
    const d = new Date(date);
    const day = d.getDay();
    const diff = d.getDate() - day + (day === 0 ? -6 : 1); 
    return new Date(d.setDate(diff));
  };

  const addDays = (date: Date, days: number) => {
    const result = new Date(date);
    result.setDate(result.getDate() + days);
    return result;
  };

  const isSameDay = (d1: Date, d2: Date) => {
    return d1.getDate() === d2.getDate() && 
           d1.getMonth() === d2.getMonth() && 
           d1.getFullYear() === d2.getFullYear();
  };

  const navigate = (direction: 'prev' | 'next') => {
    const newDate = new Date(currentDate);
    if (view === 'month') {
        newDate.setMonth(newDate.getMonth() + (direction === 'next' ? 1 : -1));
    } else if (view === 'week') {
        newDate.setDate(newDate.getDate() + (direction === 'next' ? 7 : -7));
    } else {
        newDate.setDate(newDate.getDate() + (direction === 'next' ? 1 : -1));
    }
    setCurrentDate(newDate);
  };

  const getDaysToRender = () => {
    if (view === 'day') return [currentDate];
    if (view === 'week') {
        const start = getStartOfWeek(currentDate);
        return Array.from({ length: 7 }, (_, i) => addDays(start, i));
    }
    return [];
  };

  const getFocusSessionColor = (index: number) => {
      const colorIndex = (index * 7) % FOCUS_COLORS.length; 
      return FOCUS_COLORS[colorIndex];
  };

  const getPriorityColor = (priority?: Priority) => {
      switch (priority) {
          case 'High': return 'bg-red-500';
          case 'Medium': return 'bg-orange-500';
          case 'Low': return 'bg-blue-500';
          default: return 'bg-gray-300';
      }
  };

  const handleDragStart = (e: React.DragEvent, id: string, type: 'task' | 'routine' | 'habit', origin: 'grid' | 'sidebar') => {
    if (resizingTaskId || mode === 'focus') {
        e.preventDefault();
        return;
    }
    e.dataTransfer.setData('id', id);
    e.dataTransfer.setData('type', type);
    e.dataTransfer.setData('origin', origin);
    e.dataTransfer.effectAllowed = 'move';

    // Auto-close sidebar on mobile drag to reveal calendar
    if (origin === 'sidebar' && window.innerWidth < 768) {
        setIsSidebarOpen(false);
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
  };

  const handleDropOnDay = (e: React.DragEvent, targetDate: Date) => {
    e.preventDefault();
    if (mode === 'focus') return;

    const id = e.dataTransfer.getData('id');
    const type = e.dataTransfer.getData('type');
    const origin = e.dataTransfer.getData('origin');
    
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    const offsetY = e.clientY - rect.top;
    const pxPerMin = hourHeight / 60;
    const totalMinutes = offsetY / pxPerMin;
    const snappedMinutes = Math.round(totalMinutes / 10) * 10;
    const hour = Math.floor(snappedMinutes / 60);
    const minute = snappedMinutes % 60;

    const newStart = new Date(targetDate);
    newStart.setHours(hour, minute, 0, 0);

    if (type === 'task') {
        const task = tasks.find(t => t.id === id);
        if (task) onUpdateTask({ ...task, startTime: newStart.getTime() });
    } else if (type === 'routine') {
        if (origin === 'sidebar' && onScheduleRoutine) {
            onScheduleRoutine(id, newStart.getTime());
        } else if (origin === 'grid' && onUpdateRoutine) {
            const routine = routines.find(r => r.id === id);
            if (routine) onUpdateRoutine({ ...routine, startTime: newStart.getTime() });
        }
    } else if (type === 'habit') {
        if (onScheduleHabit) onScheduleHabit(id, newStart.getTime());
    }
  };

  const handleDropOnMonthCell = (e: React.DragEvent, targetDate: Date) => {
      e.preventDefault();
      if (mode === 'focus') return;
      
      const id = e.dataTransfer.getData('id');
      const type = e.dataTransfer.getData('type');
      const origin = e.dataTransfer.getData('origin');
      const newStart = new Date(targetDate);
      
      if (type === 'task') {
          const task = tasks.find(t => t.id === id);
          if (task) {
              if (task.startTime) {
                  const old = new Date(task.startTime);
                  newStart.setHours(old.getHours(), old.getMinutes());
              } else {
                  newStart.setHours(9, 0, 0, 0);
              }
              onUpdateTask({ ...task, startTime: newStart.getTime() });
          }
      } else if (type === 'routine') {
          if (origin === 'sidebar' && onScheduleRoutine) {
              newStart.setHours(9, 0, 0, 0);
              onScheduleRoutine(id, newStart.getTime());
          } else {
              const routine = routines.find(r => r.id === id);
              if (routine && onUpdateRoutine) {
                  if (routine.startTime) {
                      const old = new Date(routine.startTime);
                      newStart.setHours(old.getHours(), old.getMinutes());
                  } else {
                      newStart.setHours(9, 0, 0, 0);
                  }
                  onUpdateRoutine({ ...routine, startTime: newStart.getTime() });
              }
          }
      } else if (type === 'habit') {
          if (onScheduleHabit) {
              newStart.setHours(9, 0, 0, 0);
              onScheduleHabit(id, newStart.getTime());
          }
      }
  };

  const handleDropOnLibrary = (e: React.DragEvent) => {
      e.preventDefault();
      setIsDraggingOverLibrary(false);
      const id = e.dataTransfer.getData('id');
      const type = e.dataTransfer.getData('type') as 'task' | 'routine' | 'habit';
      const origin = e.dataTransfer.getData('origin');
      
      if (origin === 'sidebar') return; // Don't unschedule items already in sidebar
      if (type === 'habit') return;
      if (onUnschedule) onUnschedule(id, type);
  };

  const handleBlockClick = (e: React.MouseEvent, item: Task | Routine, type: 'task' | 'routine') => {
      e.stopPropagation();
      if (mode === 'focus') return;
      if (ignoreClickRef.current || resizingTaskId) return;

      // Toggle selection for control panel
      if (selectedBlock?.id === item.id) {
          setSelectedBlock(null);
      } else {
          setSelectedBlock({ id: item.id, type });
      }
  };

  const renderMonthGrid = () => {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    const firstDay = new Date(year, month, 1);
    const startOfWeek = getStartOfWeek(firstDay);
    
    const days: Date[] = [];
    let d = new Date(startOfWeek);
    for(let i=0; i<42; i++) {
        days.push(new Date(d));
        d.setDate(d.getDate() + 1);
    }
    
    return (
        <div className="flex flex-col flex-1 h-full bg-white overflow-hidden">
             <div className="grid grid-cols-7 border-b border-gray-200 bg-gray-50/50 flex-shrink-0">
                {['S', 'M', 'T', 'W', 'T', 'F', 'S'].map(h => (
                    <div key={h} className="py-2 text-center text-xs font-bold text-gray-400 uppercase tracking-wider">{h}</div>
                ))}
             </div>
             <div className="flex-1 grid grid-cols-7 grid-rows-6 min-h-0">
                {days.map(day => {
                    const isSameMonth = day.getMonth() === month;
                    const isToday = isSameDay(day, now);
                    const dayTasks = tasks.filter(t => t.startTime && isSameDay(new Date(t.startTime), day) && (showCompleted || !t.isCompleted));
                    const dayRoutines = routines.filter(r => r.startTime && isSameDay(new Date(r.startTime), day));
                    
                    return (
                        <div 
                            key={day.toISOString()}
                            className={`border-b border-r border-surface-sage/30 p-1 relative flex flex-col gap-1 transition-colors ${!isSameMonth ? 'bg-bg-mist/30 text-neutral-slate/30' : 'bg-white hover:bg-bg-mist/50'}`}
                            onDragOver={handleDragOver}
                            onDrop={(e) => handleDropOnMonthCell(e, day)}
                        >
                            <div className="flex justify-center mb-1 shrink-0">
                                <span className={`text-[10px] font-bold w-5 h-5 flex items-center justify-center rounded-full ${isToday ? 'bg-accent-coral text-white shadow-sm shadow-accent-coral/20' : 'text-secondary-navy'}`}>
                                    {day.getDate()}
                                </span>
                            </div>
                            <div className="flex-1 overflow-y-auto custom-scrollbar space-y-1 min-h-0">
                                {dayTasks.map(task => (
                                     <div 
                                        key={task.id}
                                        draggable
                                        onDragStart={(e) => handleDragStart(e, task.id, 'task', 'grid')}
                                        onClick={(e) => handleBlockClick(e, task, 'task')}
                                        className={`flex items-center gap-1 text-[9px] px-1.5 py-0.5 rounded border truncate cursor-pointer bg-white border-gray-100 shadow-sm hover:shadow-md transition-shadow ${selectedBlock?.id === task.id ? 'ring-2 ring-black' : ''}`}
                                        style={{ borderLeftColor: task.color, borderLeftWidth: '3px' }}
                                     >
                                        {task.priority && <div className={`w-1.5 h-1.5 rounded-full shrink-0 ${getPriorityColor(task.priority)}`} />}
                                        <span className={`truncate ${task.isCompleted ? 'line-through opacity-50' : ''}`}>{task.title}</span>
                                     </div>
                                ))}
                                {dayRoutines.map(routine => (
                                    <div
                                        key={routine.id}
                                        draggable={!routine.completedAt}
                                        onDragStart={(e) => handleDragStart(e, routine.id, 'routine', 'grid')}
                                        onClick={(e) => handleBlockClick(e, routine, 'routine')}
                                        className={`text-[9px] px-1.5 py-0.5 rounded border truncate cursor-pointer bg-purple-50 border-purple-100 text-purple-700 ${selectedBlock?.id === routine.id ? 'ring-2 ring-black' : ''}`}
                                        style={{ backgroundColor: routine.id.startsWith('habit-') ? routine.color + '15' : undefined }}
                                    >
                                        {routine.title}
                                    </div>
                                ))}
                            </div>
                        </div>
                    );
                })}
             </div>
        </div>
    );
  };

  const renderTimeGrid = (days: Date[]) => {
    const hours = Array.from({ length: 24 }, (_, i) => i);
    const pxPerMin = hourHeight / 60;
    const currentMinutes = now.getHours() * 60 + now.getMinutes() + (now.getSeconds() / 60);
    const redLineTop = currentMinutes * pxPerMin;
    
    const minColWidth = view === 'week' ? 'min-w-[60px] md:min-w-0' : 'min-w-0';
    const gridMinWidth = view === 'week' ? 'min-w-[420px] md:min-w-0' : 'min-w-full';

    return (
      <div className="flex flex-col flex-1 min-h-0 bg-white relative">
        {/* Header (Days) - sticky top, syncs scroll with body */}
        <div className="flex border-b border-gray-200 bg-white z-20 shrink-0 shadow-[0_2px_4px_-2px_rgba(0,0,0,0.05)]">
            <div className="w-[50px] md:w-[60px] border-r border-gray-100 shrink-0 bg-gray-50/50 sticky left-0 z-30"></div>
            <div 
                ref={headerContainerRef}
                className="flex-1 overflow-hidden" 
            >
                <div className="grid" style={{ gridTemplateColumns: `repeat(${days.length}, 1fr)` }}>
                    {days.map(day => {
                        const isToday = isSameDay(day, now);
                        return (
                            <div key={day.toISOString()} className={`py-2 md:py-3 px-1 md:px-2 text-center border-r border-gray-100 last:border-0 bg-white group ${minColWidth}`}>
                                <div className={`text-[10px] md:text-[11px] font-bold uppercase mb-1 ${isToday ? 'text-red-500' : 'text-gray-500'}`}>
                                    <span className="md:hidden">{day.toLocaleDateString('en-US', { weekday: 'narrow' })}</span>
                                    <span className="hidden md:inline">{day.toLocaleDateString('en-US', { weekday: 'short' })}</span>
                                </div>
                                <div className={`text-lg md:text-2xl font-light w-8 h-8 md:w-10 md:h-10 flex items-center justify-center mx-auto rounded-full transition-all ${isToday ? 'bg-red-500 text-white shadow-md' : 'text-gray-900 group-hover:bg-gray-50'}`}>
                                    {day.getDate()}
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        </div>

        {/* Scrollable Body */}
        <div 
            ref={scrollContainerRef} 
            onScroll={handleBodyScroll}
            className="flex-1 overflow-y-auto overflow-x-auto custom-scrollbar relative"
        >
            <div className="flex" style={{ height: `${24 * hourHeight}px` }}>
                {/* Time Column - Sticky Left */}
                <div className="w-[50px] md:w-[60px] border-r border-gray-100 bg-white shrink-0 select-none sticky left-0 z-50">
                    {hours.map(hour => (
                        <div key={hour} className="relative border-b border-transparent box-border bg-white" style={{ height: `${hourHeight}px` }}>
                            <span className="absolute -top-2.5 right-1 md:right-2 text-[10px] md:text-xs text-gray-400 font-medium">
                                {hour === 0 ? '' : hour < 12 ? `${hour} AM` : hour === 12 ? '12 PM' : `${hour-12} PM`}
                            </span>
                        </div>
                    ))}
                    
                    {(isSameDay(now, days[0]) || days.length > 1) && (
                        <div className="absolute right-0 z-50 pointer-events-none flex items-center justify-end pr-2" style={{ top: `${redLineTop}px`, transform: 'translateY(-50%)', width: '100%' }}>
                             <span className="text-[9px] md:text-[10px] font-bold bg-red-500 text-white px-1.5 py-0.5 rounded shadow-sm relative z-20">
                                {now.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}
                            </span>
                            <div className="absolute -right-[5px] w-2.5 h-2.5 bg-red-500 rounded-full ring-2 ring-white z-10"></div>
                        </div>
                    )}
                </div>

                {/* Grid Columns */}
                <div className={`flex-1 grid relative ${gridMinWidth}`} style={{ gridTemplateColumns: `repeat(${days.length}, 1fr)` }}>
                    <div className="absolute inset-0 z-0 pointer-events-none flex flex-col">
                        {hours.map(h => (
                            <div key={h} className="border-b border-gray-100 w-full box-border" style={{ height: `${hourHeight}px` }}>
                                {hourHeight > 80 && <div className="w-full border-b border-gray-50 border-dashed" style={{ height: `${hourHeight/2}px`}}></div>}
                            </div>
                        ))}
                    </div>

                    {(isSameDay(now, days[0]) || days.length > 1) && (
                        <div className="absolute left-0 right-0 z-30 pointer-events-none" style={{ top: `${redLineTop}px` }}>
                            <div className="h-[2px] bg-accent-coral w-full shadow-[0_1px_4px_rgba(255,138,91,0.4)]"></div>
                        </div>
                    )}

                    {days.map(day => (
                        <div 
                            key={day.toISOString()} 
                            className={`relative border-r border-gray-100 last:border-0 z-10 h-full ${minColWidth}`}
                            onDragOver={handleDragOver}
                            onDrop={(e) => handleDropOnDay(e, day)}
                        >
                            {mode === 'scheduled' && (
                                <>
                                    {tasks
                                        .filter(t => t.startTime && isSameDay(new Date(t.startTime!), day) && (showCompleted || !t.isCompleted))
                                        .map(task => {
                                            const date = new Date(task.startTime!);
                                            const top = (date.getHours() * 60 + date.getMinutes()) * pxPerMin;
                                            const height = (task.duration || 60) * pxPerMin;
                                            const endTime = new Date(task.startTime! + (task.duration || 60) * 60000);
                                            const linkedProject = task.projectId ? projects.find(p => p.id === task.projectId) : null;
                                            const isSelected = selectedBlock?.id === task.id;

                                            return (
                                                <div
                                                    key={task.id}
                                                    draggable={resizingTaskId !== task.id}
                                                    onDragStart={(e) => handleDragStart(e, task.id, 'task', 'grid')}
                                                    onClick={(e) => handleBlockClick(e, task, 'task')}
                                                    className={`absolute left-0.5 right-0.5 md:left-1 md:right-1 rounded-md md:rounded-lg px-2 py-1 text-xs hover:scale-[1.01] active:scale-[0.99] shadow-sm transition-all z-20 overflow-hidden flex flex-col justify-start border border-black/5 group 
                                                        ${resizingTaskId === task.id ? 'cursor-ns-resize !scale-100 z-30 shadow-xl ring-2 ring-secondary-navy/20' : 'cursor-pointer'}
                                                        ${isSelected ? 'ring-2 ring-secondary-navy z-30 scale-[1.02] shadow-xl' : ''}
                                                        ${task.isCompleted ? 'opacity-60 grayscale saturate-50' : ''}
                                                    `}
                                                    style={{ 
                                                        top: `${top}px`, 
                                                        height: `${Math.max(height, hourHeight * 0.4)}px`,
                                                        backgroundColor: task.color || '#3b82f6',
                                                        color: '#ffffff',
                                                        boxShadow: '0 2px 4px rgba(0,0,0,0.05)'
                                                    }}
                                                >
                                                    <div className="flex flex-col h-full relative">
                                                        <div className="flex items-center gap-1 min-w-0 mb-0.5">
                                                            <div className={`w-2 h-2 rounded-full shrink-0 ${getPriorityColor(task.priority)} ring-1 ring-white/50 shadow-sm`} />
                                                            <span className={`font-bold truncate text-[10px] leading-tight flex-1 ${task.isCompleted ? 'line-through opacity-70' : ''}`}>{task.title}</span>
                                                            {task.isCompleted && <CheckCircle2 size={10} className="shrink-0" />}
                                                        </div>

                                                        <div className="text-[9px] font-medium opacity-90 leading-none truncate font-mono mb-0.5">
                                                            {date.toLocaleTimeString([], {hour:'numeric', minute:'2-digit'}).toLowerCase().replace(' ', '')} - {endTime.toLocaleTimeString([], {hour:'numeric', minute:'2-digit'}).toLowerCase().replace(' ', '')}
                                                        </div>

                                                        {height > 40 && (
                                                             <div className="mt-auto flex items-center gap-1 overflow-hidden pt-0.5">
                                                                 <span className="text-[8px] font-bold uppercase tracking-wider bg-black/10 px-1 rounded truncate">
                                                                     {task.category}
                                                                 </span>
                                                                 {linkedProject && (
                                                                     <span className="text-[8px] bg-white/20 px-1 rounded flex items-center gap-0.5 truncate max-w-[50%]">
                                                                         <Briefcase size={8} /> {linkedProject.title}
                                                                     </span>
                                                                 )}
                                                             </div>
                                                        )}
                                                    </div>
                                                    
                                                    {!task.isCompleted && <div onMouseDown={(e) => handleResizeStart(e, task)} onClick={(e) => e.stopPropagation()} className="absolute bottom-0 left-0 right-0 h-3 cursor-ns-resize flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-gradient-to-t from-black/10 to-transparent"><div className="w-8 h-1 bg-white/50 rounded-full"></div></div>}
                                                </div>
                                            );
                                        })
                                    }
                                    {routines
                                        .filter(r => r.startTime && isSameDay(new Date(r.startTime!), day))
                                        .map(routine => {
                                            const date = new Date(routine.startTime!);
                                            const durationMins = Math.ceil(routine.steps.reduce((acc, s) => acc + s.durationSeconds, 0) / 60);
                                            const top = (date.getHours() * 60 + date.getMinutes()) * pxPerMin;
                                            const height = durationMins * pxPerMin;
                                            const endTime = new Date(routine.startTime! + durationMins * 60000);
                                            const isHabit = routine.id.startsWith('habit-');
                                            const isSelected = selectedBlock?.id === routine.id;

                                            return (
                                                <div
                                                    key={routine.id}
                                                    draggable={!routine.completedAt}
                                                    onDragStart={(e) => handleDragStart(e, routine.id, 'routine', 'grid')}
                                                    onClick={(e) => handleBlockClick(e, routine, 'routine')}
                                                    className={`absolute left-0.5 right-0.5 md:left-1 md:right-1 rounded-md md:rounded-lg px-1 md:px-2 py-1 text-xs hover:scale-[1.01] active:scale-[0.99] shadow-sm transition-all z-20 overflow-hidden flex flex-col justify-start border border-black/5 cursor-pointer
                                                        ${routine.completedAt ? 'opacity-75 border-dashed saturate-75' : 'hover:brightness-95'}
                                                        ${isSelected ? 'ring-2 ring-black z-30 scale-[1.02] shadow-xl' : ''}
                                                    `}
                                                    style={{ 
                                                        top: `${top}px`, 
                                                        height: `${Math.max(height, hourHeight * 0.4)}px`,
                                                        backgroundColor: isHabit ? routine.color : '#7c3aed', 
                                                        color: '#ffffff',
                                                    }}
                                                >
                                                    <div className="flex flex-col h-full relative">
                                                        <div className="flex items-start justify-between mb-0.5 opacity-90 text-[10px]">
                                                            <div className="font-bold truncate leading-tight text-[10px] md:text-[11px] flex-1">{routine.title}</div>
                                                            {routine.completedAt && <CheckCircle2 size={10} className="shrink-0 ml-1" />}
                                                        </div>
                                                        <div className="text-[9px] font-medium opacity-90 leading-none truncate font-mono">
                                                            {date.toLocaleTimeString([], {hour:'numeric', minute:'2-digit'}).toLowerCase().replace(' ', '')} - {endTime.toLocaleTimeString([], {hour:'numeric', minute:'2-digit'}).toLowerCase().replace(' ', '')}
                                                        </div>
                                                    </div>
                                                </div>
                                            );
                                        })
                                    }
                                </>
                            )}
                            
                            {mode === 'focus' && (
                                <>
                                    {focusSessions
                                        .filter(session => isSameDay(new Date(session.startTime), day))
                                        .map((session, index) => {
                                            const date = new Date(session.startTime);
                                            const durationMins = Math.max(10, session.durationSeconds / 60);
                                            const top = (date.getHours() * 60 + date.getMinutes()) * pxPerMin;
                                            const height = durationMins * pxPerMin;
                                            return (
                                                <div
                                                    key={session.id}
                                                    className="absolute left-1 right-1 rounded-lg px-2 py-1.5 text-xs shadow-sm transition-all z-20 overflow-hidden flex flex-col justify-start border border-black/5 pointer-events-none"
                                                    style={{ top: `${top}px`, height: `${Math.max(height, hourHeight * 0.4)}px`, backgroundColor: getFocusSessionColor(index), color: '#ffffff' }}
                                                >
                                                    <div className="flex items-start justify-between mb-0.5 opacity-90 text-[10px]"><div className="font-bold truncate leading-tight text-[11px] flex-1">{session.routineTitle}</div></div>
                                                </div>
                                            );
                                        })
                                    }
                                </>
                            )}
                        </div>
                    ))}
                </div>
            </div>
        </div>
        <div className='h-20'></div>

        {/* Mobile Floating Controls */}
        {!selectedBlock && (
           <div className="md:hidden absolute right-4 bottom-20 z-30 flex flex-col gap-3 pointer-events-none">
                {/* Zoom */}
                <div className="bg-white/90 backdrop-blur-sm shadow-xl border border-gray-200 rounded-2xl flex flex-col pointer-events-auto overflow-hidden">
                     <button onClick={() => handleZoom(10)} className="p-3 text-gray-600 active:bg-gray-100 border-b border-gray-100 flex items-center justify-center"><ZoomIn size={20} /></button>
                     <button onClick={() => handleZoom(-10)} className="p-3 text-gray-600 active:bg-gray-100 flex items-center justify-center"><ZoomOut size={20} /></button>
                </div>
                {/* Scroll */}
                <div className="bg-black/90 backdrop-blur-sm text-white shadow-xl rounded-2xl flex flex-col pointer-events-auto overflow-hidden">
                     <button onClick={() => handleScroll(-hourHeight * 3)} className="p-3 active:bg-gray-800 border-b border-gray-700 flex items-center justify-center"><ChevronUp size={20} /></button>
                     <button onClick={() => handleScroll(hourHeight * 3)} className="p-3 active:bg-gray-800 flex items-center justify-center"><ChevronDown size={20} /></button>
                </div>
           </div>
        )}
      </div>
    );
  };

  return (
    <div className="w-full h-full flex flex-col relative bg-white">
      {/* Revised Header for Mobile: Rows layout */}
      <div className="flex flex-col gap-4 p-4 border-b border-gray-200 bg-white z-20 flex-shrink-0">
          
          {/* Top Row: Navigation */}
          <div className="flex items-center justify-between w-full">
               <div className="flex items-center gap-4 w-full md:w-auto justify-between md:justify-start">
                  <div className="flex bg-gray-100 rounded-lg p-1">
                      <button onClick={() => navigate('prev')} className="p-1 hover:bg-white rounded-md text-gray-500 hover:text-black transition-colors shadow-sm hover:shadow"><ChevronLeft size={16} /></button>
                      <button onClick={() => setCurrentDate(new Date())} className="px-3 text-xs font-bold text-gray-700 hover:text-black uppercase tracking-wider">Today</button>
                      <button onClick={() => navigate('next')} className="p-1 hover:bg-white rounded-md text-gray-500 hover:text-black transition-colors shadow-sm hover:shadow"><ChevronRight size={16} /></button>
                  </div>
                  <h2 className="text-lg md:text-xl font-bold text-secondary-navy tracking-tight whitespace-nowrap">
                      {currentDate.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}
                  </h2>
               </div>
               
               {/* Desktop Zoom Controls */}
               <div className="hidden md:flex items-center gap-4">
                  {view !== 'month' && (
                      <div className="flex items-center gap-1 text-gray-400">
                          <button onClick={() => setHourHeight(Math.max(40, hourHeight - 10))} className="p-2 hover:bg-gray-100 rounded-full hover:text-black transition-colors"><ZoomOut size={18}/></button>
                          <button onClick={() => setHourHeight(Math.min(150, hourHeight + 10))} className="p-2 hover:bg-gray-100 rounded-full hover:text-black transition-colors"><ZoomIn size={18}/></button>
                      </div>
                  )}
               </div>
          </div>

          {/* Bottom Row: Panels */}
          <div className="flex items-center justify-between w-full gap-2 overflow-x-auto custom-scrollbar pb-1 md:pb-0">
              
              {/* Mode Toggles */}
              <div className="flex bg-gray-100 p-1 rounded-xl shadow-inner shrink-0">
                  <button 
                      onClick={() => setMode('scheduled')}
                      className={`flex items-center justify-center gap-2 rounded-lg text-sm font-bold transition-all ${mode === 'scheduled' ? 'bg-white text-black shadow-md px-3 md:px-4 py-2' : 'text-gray-500 hover:text-gray-900 px-2 md:px-4 py-2'}`}
                  >
                      <LayoutGrid size={16} /> {mode === 'scheduled' && <span>Plan</span>}
                  </button>
                  <button 
                      onClick={() => setMode('focus')}
                      className={`flex items-center justify-center gap-2 rounded-lg text-sm font-bold transition-all ${mode === 'focus' ? 'bg-white text-black shadow-md px-3 md:px-4 py-2' : 'text-gray-500 hover:text-gray-900 px-2 md:px-4 py-2'}`}
                  >
                      <Focus size={16} /> {mode === 'focus' && <span>Focus</span>}
                  </button>
                  <div className="w-px h-6 bg-gray-300 mx-1 self-center"></div>
                  <button 
                      onClick={() => setIsSidebarOpen(!isSidebarOpen)}
                      className={`flex items-center justify-center gap-2 rounded-lg text-sm font-bold transition-all z-50 ${
                          isDraggingOverLibrary 
                              ? 'bg-red-500 text-white shadow-md scale-105 ring-2 ring-red-300 px-3 md:px-4 py-2' 
                              : isSidebarOpen 
                                  ? 'bg-black text-white shadow-md px-3 md:px-4 py-2' 
                                  : 'text-gray-500 hover:text-gray-900 hover:bg-white/50 px-2 md:px-4 py-2'
                      }`}
                      onDragOver={(e) => { e.preventDefault(); setIsDraggingOverLibrary(true); }}
                      onDragLeave={(e) => { e.preventDefault(); setIsDraggingOverLibrary(false); }}
                      onDrop={handleDropOnLibrary}
                  >
                      {isDraggingOverLibrary ? <X size={16} /> : <PanelLeft size={16} />} 
                      {isSidebarOpen && <span>{isDraggingOverLibrary ? 'Drop' : 'Library'}</span>}
                  </button>
              </div>

              {/* View Toggles */}
              <div className="flex gap-2">
                 <button 
                    onClick={() => setShowCompleted(!showCompleted)}
                    className={`flex items-center gap-2 px-3 md:px-4 py-2 text-xs font-bold uppercase rounded-xl border transition-all ${showCompleted ? 'bg-green-50 border-green-200 text-green-600' : 'bg-white border-gray-200 text-gray-400 hover:text-black hover:border-gray-300'}`}
                    title={showCompleted ? "Hide Completed Tasks" : "Show Completed Tasks"}
                 >
                    {showCompleted ? <Eye size={16} /> : <EyeOff size={16} />}
                    <span className="hidden md:inline">{showCompleted ? 'Hide Done' : 'Show Done'}</span>
                 </button>

                  <div className="flex bg-gray-100 p-1 rounded-lg shrink-0">
                      {(['day', 'week', 'month'] as CalendarView[]).map(v => (
                          <button 
                              key={v} 
                              onClick={() => setView(v)}
                              className={`px-3 md:px-4 py-1.5 text-xs font-bold uppercase rounded-md transition-all ${view === v ? 'bg-white shadow-sm text-black' : 'text-gray-500 hover:text-gray-900'}`}
                          >
                              <span className="md:hidden">{v.charAt(0).toUpperCase()}</span>
                              <span className="hidden md:inline">{v}</span>
                          </button>
                      ))}
                  </div>
              </div>
          </div>
      </div>

      <div className="flex-1 flex overflow-hidden relative min-h-0">
          {/* Sidebar Library - Refactored to relative flex item with transition */}
          <div 
              className={`border-r border-gray-200 bg-white flex-shrink-0 transition-all duration-300 ease-in-out overflow-hidden flex flex-col absolute md:relative z-[60] h-full ${isSidebarOpen ? 'w-72 opacity-100 shadow-2xl md:shadow-none' : 'w-0 border-r-0 opacity-0'}`}
          >
               {/* Fixed width container to prevent squishing content during transition */}
               <div className="w-72 flex flex-col h-full">
                   <div className="p-4 border-b border-gray-100 flex justify-between items-center bg-gray-50">
                       <h3 className="font-bold text-gray-900 text-sm flex items-center gap-2"><Book size={16} /> Library</h3>
                       <button onClick={() => setIsSidebarOpen(false)} className="p-1.5 text-gray-400 hover:text-black rounded-full hover:bg-gray-200 transition-colors"><X size={16}/></button>
                   </div>
                   
                   <div className="flex-1 overflow-y-auto p-4 space-y-6 custom-scrollbar">
                       <div>
                           <div className="flex justify-between items-center mb-2 px-1">
                               <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider">Tasks</h4>
                               <span className="bg-gray-100 text-gray-500 px-2 py-0.5 rounded-full text-[10px] font-mono font-bold">{pendingTasks.length}</span>
                           </div>
                           <div className="space-y-2">
                               {pendingTasks.map(task => (
                                   <div 
                                       key={task.id}
                                       draggable
                                       onDragStart={(e) => handleDragStart(e, task.id, 'task', 'sidebar')}
                                       className="bg-white border border-gray-200 p-3 rounded-xl text-sm shadow-sm hover:shadow-md cursor-grab active:cursor-grabbing border-l-4 group hover:border-gray-300 transition-all flex items-center justify-between"
                                       style={{ borderLeftColor: task.color || '#e5e7eb' }}
                                   >
                                       <div className="flex-1 min-w-0">
                                            <div className="font-bold text-gray-800 truncate">{task.title}</div>
                                            <div className="flex items-center gap-3 mt-2 text-xs text-gray-400 font-medium">
                                                <span className="flex items-center gap-1"><Clock size={12} /> {task.duration || 30}m</span>
                                                {task.priority && <span className="uppercase text-[9px] bg-gray-100 px-1.5 py-0.5 rounded">{task.priority}</span>}
                                            </div>
                                       </div>
                                       <button 
                                            onClick={() => handleQuickScheduleTask(task)}
                                            className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                                            title="Schedule next hour"
                                       >
                                           <CalendarPlus size={18} />
                                       </button>
                                   </div>
                               ))}
                               {pendingTasks.length === 0 && <p className="text-xs text-gray-400 italic text-center py-4">No pending tasks.</p>}
                           </div>
                       </div>

                       <div>
                           <div className="flex justify-between items-center mb-2 px-1">
                               <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider">Routines</h4>
                               <span className="bg-purple-50 text-purple-600 px-2 py-0.5 rounded-full text-[10px] font-mono font-bold">{recurringRoutines.length}</span>
                           </div>
                           <div className="space-y-2">
                               {recurringRoutines.map(routine => (
                                   <div 
                                       key={routine.id}
                                       draggable
                                       onDragStart={(e) => handleDragStart(e, routine.id, 'routine', 'sidebar')}
                                       className="bg-purple-50 border border-purple-100 p-3 rounded-xl text-sm shadow-sm hover:shadow-md cursor-grab active:cursor-grabbing group transition-all flex items-center justify-between"
                                   >
                                       <div className="flex-1 min-w-0">
                                           <div className="font-bold text-purple-900 truncate">{routine.title}</div>
                                           <div className="flex items-center gap-2 mt-2 text-xs text-purple-500 font-medium">
                                               <Layers size={12} /> {routine.steps.length} Steps
                                           </div>
                                       </div>
                                       <button 
                                            onClick={() => handleQuickScheduleRoutine(routine)}
                                            className="p-2 text-purple-300 hover:text-purple-600 hover:bg-purple-100 rounded-lg transition-colors"
                                            title="Schedule next hour"
                                       >
                                           <CalendarPlus size={18} />
                                       </button>
                                   </div>
                               ))}
                           </div>
                       </div>
                       
                       <div>
                           <div className="flex justify-between items-center mb-2 px-1">
                               <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider">Habits</h4>
                               <span className="bg-gray-100 text-gray-500 px-2 py-0.5 rounded-full text-[10px] font-mono font-bold">{habits.length}</span>
                           </div>
                           <div className="space-y-2">
                               {habits.map(habit => (
                                   <div 
                                       key={habit.id}
                                       draggable
                                       onDragStart={(e) => handleDragStart(e, habit.id, 'habit', 'sidebar')}
                                       className="bg-white border border-gray-200 p-3 rounded-xl text-sm shadow-sm hover:shadow-md cursor-grab active:cursor-grabbing flex items-center justify-between gap-3 hover:border-gray-300 transition-all"
                                   >
                                       <div className="flex items-center gap-3 flex-1 min-w-0">
                                            <div className="w-3 h-3 rounded-full shadow-sm shrink-0" style={{ backgroundColor: habit.color }}></div>
                                            <span className="truncate font-medium text-gray-700">{habit.title}</span>
                                       </div>
                                       <button 
                                            onClick={() => handleQuickScheduleHabit(habit)}
                                            className="p-2 text-gray-400 hover:text-green-600 hover:bg-green-50 rounded-lg transition-colors"
                                            title="Schedule next hour"
                                       >
                                           <CalendarPlus size={18} />
                                       </button>
                                   </div>
                               ))}
                           </div>
                       </div>
                   </div>
               </div>
          </div>
          
          {/* Main Calendar Grid - Flex 1 ensures it takes remaining space and resizes */}
          <div className="flex-1 flex flex-col min-w-0 bg-white relative">
              {view === 'month' ? renderMonthGrid() : renderTimeGrid(getDaysToRender())}
          </div>
      </div>
      
      {/* Mobile Touch Control Panel - Only visible when an item is selected */}
      {selectedBlock && (
          <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 shadow-[0_-10px_40px_-15px_rgba(0,0,0,0.1)] z-[100] pb-safe animate-slide-in-up">
              <div className="p-4 space-y-4">
                  <div className="flex justify-between items-center border-b border-gray-100 pb-2">
                       <div className="flex items-center gap-2">
                           <Move size={16} className="text-gray-500"/> 
                           <span className="font-bold text-gray-900 truncate max-w-[200px]">
                               {selectedBlock.type === 'task' 
                                 ? tasks.find(t => t.id === selectedBlock.id)?.title 
                                 : routines.find(r => r.id === selectedBlock.id)?.title}
                           </span>
                       </div>
                       <button onClick={() => setSelectedBlock(null)} className="p-1 text-gray-400 hover:text-black bg-gray-100 rounded-full">
                           <X size={18} />
                       </button>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4">
                      {/* Direction Pad */}
                      <div className="bg-gray-50 p-3 rounded-2xl flex flex-col items-center justify-center gap-2">
                          <button onClick={() => moveSelectedItem(-15)} className="p-2 bg-white border border-gray-200 rounded-lg shadow-sm hover:bg-gray-100 active:scale-95"><ArrowUp size={20}/></button>
                          <div className="flex gap-2">
                              <button onClick={() => shiftSelectedItemDay(-1)} className="p-2 bg-white border border-gray-200 rounded-lg shadow-sm hover:bg-gray-100 active:scale-95"><ArrowLeft size={20}/></button>
                              <div className="w-10 h-10 flex items-center justify-center text-xs font-bold text-gray-400"><Clock size={16}/></div>
                              <button onClick={() => shiftSelectedItemDay(1)} className="p-2 bg-white border border-gray-200 rounded-lg shadow-sm hover:bg-gray-100 active:scale-95"><ArrowRight size={20}/></button>
                          </div>
                          <button onClick={() => moveSelectedItem(15)} className="p-2 bg-white border border-gray-200 rounded-lg shadow-sm hover:bg-gray-100 active:scale-95"><ArrowDown size={20}/></button>
                      </div>

                      <div className="flex flex-col gap-3">
                          {/* Duration Controls - Only for Tasks */}
                          {selectedBlock.type === 'task' ? (
                              <div className="bg-gray-50 p-3 rounded-2xl flex items-center justify-between">
                                  <button onClick={() => resizeSelectedItem(-15)} className="p-2 bg-white border border-gray-200 rounded-lg shadow-sm active:scale-95"><Minus size={18}/></button>
                                  <span className="text-xs font-bold text-gray-500 uppercase">Length</span>
                                  <button onClick={() => resizeSelectedItem(15)} className="p-2 bg-white border border-gray-200 rounded-lg shadow-sm active:scale-95"><Plus size={18}/></button>
                              </div>
                          ) : (
                              <div className="bg-gray-50 p-3 rounded-2xl flex items-center justify-center text-xs font-medium text-gray-400 h-[62px]">
                                  Fixed Duration
                              </div>
                          )}

                          {/* Actions */}
                          <div className="flex gap-2 flex-1">
                              <button onClick={unscheduleSelectedItem} className="flex-1 bg-red-50 text-red-500 rounded-xl flex items-center justify-center font-bold text-xs flex-col gap-1 active:scale-95 border border-red-100">
                                  <CalendarOff size={18} /> Unschedule
                              </button>
                              <button 
                                onClick={startSelectedItem} 
                                className="flex-1 bg-black text-white rounded-xl flex items-center justify-center font-bold text-xs flex-col gap-1 active:scale-95 shadow-lg"
                              >
                                  <PlayCircle size={18} /> Start
                              </button>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      )}
    </div>
  );
};
